import 'dart:async';
import 'dart:io';
import 'dart:math' as math;
import 'dart:ui' as ui;
import 'package:flutter/painting.dart';
import 'package:path/path.dart' as p;

import '../../models/project_model.dart';
import '../ffmpeg/ffmpeg_service.dart';
import '../renderer/karaoke_renderer.dart';

class CancellationToken {
  bool isCancelled = false;
  void cancel() => isCancelled = true;
}

class ExportProgress {
  const ExportProgress({
    required this.currentFrame,
    required this.totalFrames,
    required this.progress,
    required this.fps,
    required this.elapsed,
  });

  final int currentFrame;
  final int totalFrames;
  final double progress;
  final double fps;
  final Duration elapsed;
}

class ExportEngine {
  ExportEngine({this.ffmpegService, KaraokeRenderer? renderer})
    : renderer = renderer ?? KaraokeRenderer();

  final FfmpegService? ffmpegService;
  final KaraokeRenderer renderer;

  // --- SUBTITLE EXPORTS ---

  String exportAss(ProjectModel project) {
    final buffer = StringBuffer();
    buffer.writeln('[Script Info]');
    buffer.writeln('; Script generated by KaraStudio');
    buffer.writeln('Title: ${project.name}');
    buffer.writeln('ScriptType: v4.00+');
    buffer.writeln('WrapStyle: 0');
    buffer.writeln('ScaledBorderAndShadow: yes');
    buffer.writeln('YCbCr Matrix: TV.709');
    buffer.writeln('PlayResX: ${project.canvasWidth}');
    buffer.writeln('PlayResY: ${project.canvasHeight}');
    buffer.writeln();

    buffer.writeln('[V4+ Styles]');
    buffer.writeln(
      'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding',
    );

    for (final style in project.styles) {
      final pri = _toAssColor(style.inactiveColorValue);
      final sec = _toAssColor(style.activeColorValue);
      final out = _toAssColor(style.outlineColorValue);
      final shadow = _toAssColor(style.shadowColorValue);

      final align = switch (style.alignment) {
        SubtitleAlignment.left => 1,
        SubtitleAlignment.center => 2,
        SubtitleAlignment.right => 3,
      };

      buffer.writeln(
        'Style: ${style.name},${style.fontFamily},${style.fontSize.round()},$pri,$sec,$out,$shadow,${style.fontWeight >= 700 ? -1 : 0},${style.isItalic ? -1 : 0},${style.isUnderline ? -1 : 0},0,100,100,${style.letterSpacing.round()},0,1,${style.outlineWidth.round()},${style.shadowBlur > 0 ? 2 : 0},$align,20,20,40,1',
      );
    }
    buffer.writeln();

    buffer.writeln('[Events]');
    buffer.writeln(
      'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text',
    );

    for (var i = 0; i < project.lyricLines.length; i++) {
      final line = project.lyricLines[i];
      final startUs = line.startUs ?? 0;
      final endUs = line.endUs ?? (startUs + 4000000);

      final startStr = _formatAssTime(startUs);
      final endStr = _formatAssTime(endUs);

      final actor = project.actors.firstWhere(
        (a) => a.id == line.actorId,
        orElse: () => project.actors.first,
      );
      final style = project.styles.firstWhere(
        (s) => s.id == line.styleId || s.id == actor.styleId,
        orElse: () => project.styles.first,
      );

      // Build karaoke tags
      final textBuffer = StringBuffer();
      var cursorUs = startUs;

      for (final token in line.tokens) {
        final tStart = token.startUs ?? cursorUs;
        final tEnd = token.endUs ?? (tStart + 400000);
        final durCs = ((tEnd - tStart) / 10000).round();
        cursorUs = tEnd;

        textBuffer.write('{\\k$durCs}${token.text} ');
      }

      final dialogueText = textBuffer.isNotEmpty
          ? textBuffer.toString().trim()
          : line.text;

      buffer.writeln(
        'Dialogue: 0,$startStr,$endStr,${style.name},${actor.name},0,0,0,,$dialogueText',
      );
    }

    return buffer.toString();
  }

  String exportSrt(ProjectModel project) {
    final buffer = StringBuffer();
    var index = 1;

    for (final line in project.lyricLines) {
      final startUs = line.startUs ?? 0;
      final endUs = line.endUs ?? (startUs + 4000000);

      buffer.writeln('$index');
      buffer.writeln('${_formatSrtTime(startUs)} --> ${_formatSrtTime(endUs)}');
      buffer.writeln(line.text);
      buffer.writeln();
      index++;
    }

    return buffer.toString();
  }

  String exportLrc(ProjectModel project, {bool includeWordTiming = true}) {
    final buffer = StringBuffer();
    buffer.writeln('[ti:${project.name}]');
    buffer.writeln('[by:KaraStudio]');

    for (final line in project.lyricLines) {
      final startUs = line.startUs ?? 0;
      final startTag = _formatLrcTime(startUs);

      if (includeWordTiming && line.tokens.isNotEmpty) {
        final lineBuf = StringBuffer(startTag);
        for (final token in line.tokens) {
          if (token.startUs != null) {
            lineBuf.write(
              '<${_formatLrcTimeNoBrackets(token.startUs!)}>${token.text} ',
            );
          } else {
            lineBuf.write('${token.text} ');
          }
        }
        buffer.writeln(lineBuf.toString().trim());
      } else {
        buffer.writeln('$startTag ${line.text}');
      }
    }

    return buffer.toString();
  }

  // --- DETERMINISTIC VIDEO / TRANSPARENT EXPORT ---

  Future<void> exportVideo({
    required ProjectModel project,
    required String outputPath,
    required String format, // 'mp4', 'mov', 'webm', 'png_seq'
    required int width,
    required int height,
    required double fps,
    int startUs = 0,
    int? endUs,
    required void Function(ExportProgress progress) onProgress,
    required CancellationToken cancellationToken,
  }) async {
    final effectiveEndUs =
        endUs ?? project.audio?.durationUs ?? project.video?.durationUs ?? 0;
    final totalDurationUs = math.max(1000000, effectiveEndUs - startUs);
    final totalFrames = (totalDurationUs * fps / 1000000).round();

    final isTransparent =
        format == 'mov' || format == 'webm' || format == 'png_seq';
    final service = ffmpegService ?? FfmpegService();

    Process? encoderProcess;
    IOSink? stdin;
    String? pngSeqDir;
    final backgroundVideoPath =
        !isTransparent &&
            project.video != null &&
            await File(project.video!.path).exists()
        ? project.video!.path
        : null;

    if (format == 'png_seq') {
      pngSeqDir = outputPath;
      await Directory(pngSeqDir).create(recursive: true);
    } else {
      encoderProcess = await service.startRawRgbaVideoEncoder(
        outputPath: outputPath,
        width: width,
        height: height,
        fps: fps,
        audioPath: isTransparent ? null : project.audio?.path,
        backgroundVideoPath: backgroundVideoPath,
        startUs: startUs,
        isTransparent: isTransparent,
        format: format,
      );
      stdin = encoderProcess.stdin;
    }

    final stopwatch = Stopwatch()..start();
    final canvasSize = Size(width.toDouble(), height.toDouble());

    ui.Image? bgImage;
    if (!isTransparent &&
        backgroundVideoPath == null &&
        project.backgroundImage != null &&
        File(project.backgroundImage!.path).existsSync()) {
      try {
        final bytes = await File(project.backgroundImage!.path).readAsBytes();
        final codec = await ui.instantiateImageCodec(bytes);
        final frameInfo = await codec.getNextFrame();
        bgImage = frameInfo.image;
      } catch (_) {}
    }

    try {
      for (var f = 0; f < totalFrames; f++) {
        if (cancellationToken.isCancelled) {
          if (encoderProcess != null) {
            encoderProcess.kill();
          }
          throw Exception('Quá trình xuất đã bị hủy bởi người dùng.');
        }

        final t = startUs + ((f * 1000000) / fps).round();

        // 1. Offscreen Render Skia Picture
        final recorder = ui.PictureRecorder();
        final canvas = Canvas(
          recorder,
          Rect.fromLTWH(0, 0, width.toDouble(), height.toDouble()),
        );

        if (bgImage != null) {
          final fitted = applyBoxFit(
            BoxFit.cover,
            Size(bgImage.width.toDouble(), bgImage.height.toDouble()),
            canvasSize,
          );
          final source = Alignment.center.inscribe(
            fitted.source,
            Rect.fromLTWH(
              0,
              0,
              bgImage.width.toDouble(),
              bgImage.height.toDouble(),
            ),
          );
          final destination = Alignment.center.inscribe(
            fitted.destination,
            Offset.zero & canvasSize,
          );
          canvas.drawImageRect(bgImage, source, destination, Paint());
        }

        renderer.render(
          canvas: canvas,
          canvasSize: canvasSize,
          project: project,
          timeUs: t,
          isPreview: false,
        );

        final picture = recorder.endRecording();
        final image = await picture.toImage(width, height);

        if (format == 'png_seq') {
          final pngData = await image.toByteData(
            format: ui.ImageByteFormat.png,
          );
          if (pngData != null) {
            final framePath = p.join(
              pngSeqDir!,
              'frame_${(f + 1).toString().padLeft(6, '0')}.png',
            );
            await File(framePath).writeAsBytes(
              pngData.buffer.asUint8List(
                pngData.offsetInBytes,
                pngData.lengthInBytes,
              ),
            );
          }
        } else {
          final rawData = await image.toByteData(
            format: ui.ImageByteFormat.rawRgba,
          );
          if (rawData != null && stdin != null) {
            stdin.add(
              rawData.buffer.asUint8List(
                rawData.offsetInBytes,
                rawData.lengthInBytes,
              ),
            );
            await stdin.flush();
          }
        }

        picture.dispose();
        image.dispose();

        final elapsed = stopwatch.elapsed;
        final currentFps = (f + 1) / (elapsed.inMicroseconds / 1000000.0);

        onProgress(
          ExportProgress(
            currentFrame: f + 1,
            totalFrames: totalFrames,
            progress: (f + 1) / totalFrames,
            fps: currentFps,
            elapsed: elapsed,
          ),
        );
      }

      if (stdin != null) {
        await stdin.close();
      }
      if (encoderProcess != null) {
        final exitCode = await encoderProcess.exitCode;
        if (exitCode != 0) {
          throw FfmpegException(
            'FFmpeg kết thúc với lỗi (exit code: $exitCode).',
          );
        }
      }
    } finally {
      bgImage?.dispose();
      stopwatch.stop();
    }
  }

  // --- TIME FORMAT HELPERS ---

  static String _toAssColor(int colorValue) {
    // ARGB -> &HAABBGGRR&
    final a = (255 - ((colorValue >> 24) & 0xFF))
        .toRadixString(16)
        .padLeft(2, '0')
        .toUpperCase();
    final r = ((colorValue >> 16) & 0xFF)
        .toRadixString(16)
        .padLeft(2, '0')
        .toUpperCase();
    final g = ((colorValue >> 8) & 0xFF)
        .toRadixString(16)
        .padLeft(2, '0')
        .toUpperCase();
    final b = (colorValue & 0xFF)
        .toRadixString(16)
        .padLeft(2, '0')
        .toUpperCase();
    return '&H$a$b$g$r&';
  }

  static String _formatAssTime(int timeUs) {
    final d = Duration(microseconds: timeUs);
    final h = d.inHours;
    final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    final cs = (d.inMilliseconds.remainder(1000) ~/ 10).toString().padLeft(
      2,
      '0',
    );
    return '$h:$m:$s.$cs';
  }

  static String _formatSrtTime(int timeUs) {
    final d = Duration(microseconds: timeUs);
    final h = d.inHours.toString().padLeft(2, '0');
    final m = d.inMinutes.remainder(60).toString().padLeft(2, '0');
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    final ms = d.inMilliseconds.remainder(1000).toString().padLeft(3, '0');
    return '$h:$m:$s,$ms';
  }

  static String _formatLrcTime(int timeUs) {
    return '[${_formatLrcTimeNoBrackets(timeUs)}]';
  }

  static String _formatLrcTimeNoBrackets(int timeUs) {
    final d = Duration(microseconds: timeUs);
    final m = (d.inHours * 60 + d.inMinutes.remainder(60)).toString().padLeft(
      2,
      '0',
    );
    final s = d.inSeconds.remainder(60).toString().padLeft(2, '0');
    final cs = (d.inMilliseconds.remainder(1000) ~/ 10).toString().padLeft(
      2,
      '0',
    );
    return '$m:$s.$cs';
  }
}
